# Generated by Django 2.2 on 2019-12-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='イメージ')),
            ],
            options={
                'db_table': 'animal_image',
            },
        ),
    ]
